{{- if (and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "navidrome.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "navidrome.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
    storageClassName: {{ .Values.persistence.data.storageClassName | quote }}
{{- end }}