apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    lastfm_apikey: {{ .Values.lastfm.encryptedApikey | quote }}
    lastfm_secret: {{ .Values.lastfm.encryptedSecret | quote }}
  template:
    metadata:
      name: {{ .Values.secretName }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
