apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/external-dns      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: external-dns
      parameters:
        - name: global.security.allowInsecureImages
          value: "true"
        - name: image.registry
          value: "registry.k8s.io"
        - name: image.repository
          value: "external-dns/external-dns"
        - name: image.tag
          value: "v0.18.0"
        - name: provider
          value: "rfc2136"
        - name: rfc2136.host
          value: "192.168.31.100"
        - name: rfc2136.port
          value: "53"
        - name: rfc2136.zone
          value: "pengdake.top"
        - name: rfc2136.tsigSecret
          value: "QLErbZUtNtEsCk5a4ExIyP6uM1WgVqXc1FxRyCDGaS4="
        - name: rfc2136.tsigAlgorithm
          value: "hmac-sha256"
        - name: rfc2136.tsigKeyname
          value: "externaldns"
        - name: policy
          value: "upsert-only"
        - name: txtOwnerId
          value: "k3s" 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
