apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/harbor      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: harbor
      parameters:
      - name: updateStrategy.type
        value: "Recreate"
      - name: expose.type
        value: "ingress"
      - name: expose.tls.enabled
        value: "true"
      - name: expose.tls.certSource
        value: "secret"
      - name: expose.tls.secret.secretName
        value: "harbor-ingress"
      - name: expose.ingress.hosts.core
        value: "harbor.pengdake.xyz"
      - name: expose.externalURL
        value: "harbor.pengdake.xyz"
      - name: persistence.persistenceVolumeClaim.registry.size
        value: "30Gi"
      - name: proxy.httpProxy
        value: "http://192.168.31.90:7890"
      - name: proxy.httpsProxy
        value: "http://192.168.31.90:7890"
      - name: metrics.enabled
        value: "true"
      - name: metrics.serviceMonitor.enabled
        value: "true"
      - name: database.type
        value: "external"
      - name: database.external.host
        value: "cloudnative-postgresql-cluster-rw.default.svc.cluster.local"
      - name: database.external.port
        value: "5432"
      - name: database.external.username
        value: "app"
      - name: database.external.password
        value: "yX1GEbvyGRT3O6kW7Qhx8Wiznc4OFE2kKSuufJqbgDugXwi4c4tCaCkzUvKIsw2x"
      - name: redis.type
        value: "external"
      - name: redis.external.sentinelMasterSet
        value: "mymaster"
      - name: redis.external.addr
        value: "redis-node-0.redis-headless.default.svc.cluster.local:26379,redis-node-1.redis-headless.default.svc.cluster.local:26379,redis-node-2.redis-headless.default.svc.cluster.local:26379"
      - name: redis.external.password
        value: "abc123" # 生产环境建议使用 Argo CD Secrets 或 Values 文件

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true