apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/jellyfin      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: jellyfin
      parameters:
        - name: persistence.enabled
          value: "true"
        - name: persistence.media.enabled
          value: "true"
        - name: persistence.media.storageClass
          value: "nfs-client"
        - name: persistence.media.size
          value: "600Gi"
        - name: deploymentStrategy.type
          value: "Recreate"
        # 使用已有的persistent volume claim，注释掉上面关于persistence.media的参数，并取消下面的注释 
        # - name: persistence.media.existingClaim
        #  value: ""

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
