apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/metallb      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: metallb
      parameters:
      - name: prometheus.namespace
        value: "default"
      - name: prometheus.serviceMonitor.enabled
        value: "false"
      - name: speaker.frr.enabled
        value: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true