apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/minio      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: minio
      parameters:
      - name: replicas
        value: "4"
      - name: size
        value: "100Gi"
      - name: ingress.enabled
        value: "true"
      - name: consoleIngress.enabled
        value: "true"
      - name: rootUser
        value: "admin"
      - name: rootPassword
        value: "abc123"
      - name: metrics.enabled
        value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: minio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  syncOptions:
    - CreateNamespace=true