apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd    # 必须是 argocd 命名空间
spec:
  project: default
  source:
    repoURL: https://github.com/pengdake/home-chart.git
    targetRevision: main
    path: charts/nextcloud      # 指向你自定义 Helm Chart 的路径
    helm:
      releaseName: nextcloud
      parameters:
        - name: replicaCount
          value: "1"
        - name: persistence.enabled
          value: "true"
        - name: persistence.nextcloudData.enabled
          value: "true"
        - name: persistence.nextcloudData.storageClass
          value: "nfs-client"
        - name: persistence.nextcloudData.size
          value: "100Gi"
        - name: nextcloud.trustedDomains[0]
          value: "*"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
