# Default values for navidrome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: deluan/navidrome
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 4533

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /app
    port: http
  initialDelaySeconds: 30   # 等应用启动
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /app
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: 
- name: data-volume
  persistentVolumeClaim:
    claimName: navidrome-data
- name: music-volume
  persistentVolumeClaim:
    claimName: navidrome-music
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
- name: data-volume
  mountPath: /data
- name: music-volume
  mountPath: /music
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  data:
    enabled: true
    existingClaim:          # 有现成PVC就填它的名字，否则留空自动创建
    storageClassName: nfs-client
    accessModes:
      - ReadWriteMany
    size: 1Gi
  music:
    enabled: true
    existingClaim: navidrome-music
    storageClassName: nfs-client
    accessModes:
      - ReadWriteMany
    size: 10Gi

env:
  - name: ND_PROMETHEUS_ENABLED
    value: "true"
  - name: ND_PROMETHEUS_METRICSPATH
    value: "/metrics"
  - name: ND_TRANSCODINGCACHESIZE
    value: "300MB"
  - name: ND_IMAGECACHESIZE
    value: "300MB"
  

secretName: navidrome-secret

lastfm:
  encryptedApikey: AgA615HrUiJgoClzEE/i09VBejl9B56+1MNpYCWO9q9dIXjU2Dn9ZvdR7ToEl641nanfk0TmP5fEo2d34KmwVHTW4b2oeVaGvDuWijBxQgSsF2J2akLzZuCbxHMopiZFP7wrndcCEhOagnbQ6od5lkPPIU5IhRjgfSuOcXXlc/wsK6EVUnZoyLW0x0O9AcK8us3RYHn6Sxi1dY7Wt8pSbM9X9b/pJABHfZxJuTap1vmfuyQzJotT3F+uQCIojO9jo+APg192yF0FfI8vjto8ZmvKmxcewdRjuyuS3AUq6m1/q/U7X1V0YT56T07TqLJy6A8D+v/xFBU8WFMVVHYkY/5wfEafDa8aWIZ2KDZpcNhY655hExw5LMknXixUdW5RAdnAXy4vYIht8Q3vAp5qpUdi9j+v7n2+D35Ecg9Pa67CKjj2dIF/owLXKFoLHR29OzG70orAl58BjuWFZI8urStf5SrFbLaCj96J7zAIQVKChvEGU0hIX9fyobXTztV3FP9MHkqN5BK/dRhE+6LuWph/4q8LcNp3BVdyqEtmUUwp0ozuIcXRBNK+uRDjpdkWYDpq+E/kA/KKSKsh+SlRZ9QfyMZnwmbzKYKEpRc5m879ZwovT5p2smXhXMwn6SNY0CX2Kw1VSpnzOEL0YvGlMP12Ur1oqGyS1tMSCRAJWpEI7b/jsPfp1+IjPc4P7WjUgmUzKys8zh1Zb1Y2ApgUt6k/lS91FEHDLghXIHBQ92IF9A==
  encryptedSecret: AgAWfE3gO9aOhrCy9UkQ7IefX6DZxecHsyUdzD37Sd6plo5Z+YsRUG6athwfZMQA9Gd1YQDBcOqZnnrpWnQMkPRrd7FfPhms7xaOxEcepEsDqKB8HljiZN1tukqv6RWhQo+WYd3ovRczF4E5mDcSRR4tg7T/N6KLTpeedMnLbGuYh+Ms0+G2uqJv3Gewx8pDuZruRhiGl+hKcWxPWK/8owStMxDCG6zZaIyufpWPLHuKrvDFLPijU79QvG0AOKUo5wgHqMtD1PnNazB/ugpLAt8Z3V+YCvyU40HyX/GgsZTSlbOFQBzfLFdDBCcgdbVto80luYSusuipm2nWN88w6bjduzhtx8F8Zjay5PlnGXnS+HnI2Uqgc42cA8+sp5qQbeHK0mWasFBYiFUDxrV9lAKmTVOajrpOJB0Xb04prE4FH1nreN2xHu2oxOyXR9+8oxzB9orbjYmfp0BJ0LbUOaAQXH41yZe2gyYuyYe9w3e+OPwyrJ2mail5FoJWoXjlrSv6p8CFIp0RubhHkS3ZUKDykB/SXyk3bdrbemajmWpTzUPUD6gfdzhz6EsibTf0R70EjNmvE4lullzn0QUy7C+ru9B8jZLQC2VU309OAR8M0ImXQcEZqf32kXyI1LKH82ULtb8DmvGB6I92zkj7lUrBtutXiG4zA0zdPnEr9OqhM83IrvIXq2pT68Hx4Rpk/4vnvJIvVX2rQNCKRoql6A1/gJhj43F6LN2/fCr0K05Tfg==